apiVersion: v2
name: game-server-deployment-discord-bot
type: application
version: "1.0.0"
appVersion: "latest"
dependencies:
  - name: redis
    version: "16.5.1"
    repository: https://charts.bitnami.com/bitnami
