version: "3.8"

networks:
  redis-bot:
  redis-job:

volumes:
  terraform:
  sshkey:

services:
  redis:
    image: redis:alpine
    init: true
    read_only: true
    networks:
      - redis-bot
      - redis-job
  job-runner:
    build:
      context: .
      target: runtime-job-runner
    image: ghcr.io/strayer/game-server-deployment-discord-bot/job-runner:latest
    init: true
    read_only: true
    networks:
      - redis-job
    volumes:
      - terraform:/terraform
      - sshkey:/sshkey
      - ./backup:/backup
    tmpfs:
      - /tmp
      - /root/.ansible
      - /root/.ssh
    environment:
      - RQ_REDIS_URL=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379/1
      - BACKUP_PATH=/backup
    env_file: ./job-runner.env
  discord-bot:
    build:
      context: .
      target: runtime-discord-bot
    image: ghcr.io/strayer/game-server-deployment-discord-bot/discord-bot:latest
    init: true
    read_only: true
    networks:
      - redis-bot
    environment:
      - RQ_REDIS_URL=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379/1
      - ENV=dev
    env_file: ./discord-bot.env
