---

- name: create telegraf configuration directory
  file:
    path: /etc/telegraf
    owner: root
    group: root
    mode: "755"
    state: directory
- name: install telegraf configuration
  template:
    dest: /etc/telegraf/telegraf.conf
    mode: "u=rw,og=r"
    owner: root
    group: root
    src: templates/telegraf.conf.j2
- name: download telegraf deb
  get_url:
    url: https://dl.influxdata.com/telegraf/releases/telegraf_1.20.4-1_amd64.deb
    dest: /root/telegraf.deb
    checksum:  sha256:667bed3e97d2c914c34a14c544bd0c767353879c0427c65fa82d53da9420555d
  register: download_telegraf_deb
- name: install telegraf # noqa no-handler
  apt:
    deb: /root/telegraf.deb
  when: download_telegraf_deb.changed
