---

- name: create valheim group
  ansible.builtin.group:
    name: valheim
    gid: 3500
- name: create valheim user
  ansible.builtin.user:
    name: valheim
    uid: 3500
    group: valheim
    create_home: no
- name: set up valheim home symlink
  file:
    dest: /home/valheim
    src: /mnt/HC_Volume_{{ lookup('env', 'HCLOUD_VOLUME_ID') }}/valheim-home
    owner: valheim
    group: valheim
    state: link
- name: set up valheim dedicated server install dir symlink
  file:
    dest: /opt/valheim
    src: /mnt/HC_Volume_{{ lookup('env', 'HCLOUD_VOLUME_ID') }}/valheim-server
    owner: steam
    group: steam
    state: link
- name: download valheim dedicated server
  command: |
    /opt/steamcmd/steamcmd.sh +force_install_dir "/opt/valheim" +login anonymous +app_update 896660 +quit
  become: yes
  become_user: steam
  register: install_valheim
  changed_when: "'Success! App \\'896660\\' already up to date.' not in install_valheim.stdout"
- name: copy systemd unit
  template:
    src: templates/valheim.service.j2
    dest: /etc/systemd/system/valheim.service
    owner: root
    group: root
    mode: 0644
  register: copy_valheim_systemd_unit
- name: reload systemd daemon # noqa no-handler
  ansible.builtin.systemd:
    daemon_reload: yes
  when: copy_valheim_systemd_unit.changed
- name: enable valheim service
  ansible.builtin.systemd:
    name: valheim
    state: started
    enabled: yes
